Registro_server/Registro_server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('autenticaciones.urls')), 
    path('sequences/', include('sequences.urls')), 
]

Registro_server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('autenticaciones.urls')), 
    path('sequences/', include('sequences.urls')), 
]

autenticaciones/urls.py
from django.urls import path
from . import views

app_name = 'autenticaciones'
urlpatterns = [
    path('', views.auth_view, name='auth_view'),  
    path('home/', views.home, name='home'),
    path('information/', views.information_view, name='information'),
    path('logout/', views.logout, name='logout'),
    path('about/', views.about_view, name='about'),
]

sequences/urls.py
from django.urls import path
from . import views

app_name='sequences'
urlpatterns = [
    path('sequence/', views.sequence_view, name='sequence' ),
    path('results/', views.results_view , name='results_view'),
    path('about/', views.about_view, name='about'), 
]

Registro_server/autenticaciones/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser , BaseUserManager, PermissionsMixin
from django.core.exceptions import ValidationError
import re

class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        """Crea y devuelve un usuario con un correo electrónico y contraseña."""
        if not email:
            raise ValueError('El correo electrónico debe ser proporcionado')
        if not username:
            raise ValueError('El nombre de usuario debe ser proporcionado')

        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)  # Almacena la contraseña de forma segura
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None, **extra_fields):
        """Crea y devuelve un superusuario con un correo electrónico y contraseña."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, username, password, **extra_fields)

class CustomUser (AbstractBaseUser , PermissionsMixin):
    """Modelo de usuario personalizado."""
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=30, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()  # Asigna el CustomUser Manager

    USERNAME_FIELD = 'email'  # Usa el correo electrónico como el campo único para autenticación
    REQUIRED_FIELDS = ['username']  # Campos requeridos al crear un superusuario

    def clean(self):
        """Valida la unicidad del correo electrónico y el nombre de usuario."""
        super().clean()
        if CustomUser .objects.filter(email=self.email).exists():
            raise ValidationError("Este correo ya está en uso.")
        
        if CustomUser .objects.filter(username=self.username).exists():
            raise ValidationError("Este nombre de usuario ya está en uso.")

    def validate_password(self, password):
        """Valida que la contraseña contenga al menos un carácter especial."""
        if not re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
            raise ValidationError("La contraseña debe contener al menos un carácter especial.")

autenticaciones/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser , BaseUserManager, PermissionsMixin
from django.core.exceptions import ValidationError
import re

class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        """Crea y devuelve un usuario con un correo electrónico y contraseña."""
        if not email:
            raise ValueError('El correo electrónico debe ser proporcionado')
        if not username:
            raise ValueError('El nombre de usuario debe ser proporcionado')

        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)  # Almacena la contraseña de forma segura
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None, **extra_fields):
        """Crea y devuelve un superusuario con un correo electrónico y contraseña."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, username, password, **extra_fields)

class CustomUser (AbstractBaseUser , PermissionsMixin):
    """Modelo de usuario personalizado."""
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=30, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()  # Asigna el CustomUser Manager

    USERNAME_FIELD = 'email'  # Usa el correo electrónico como el campo único para autenticación
    REQUIRED_FIELDS = ['username']  # Campos requeridos al crear un superusuario

    def clean(self):
        """Valida la unicidad del correo electrónico y el nombre de usuario."""
        super().clean()
        if CustomUser .objects.filter(email=self.email).exists():
            raise ValidationError("Este correo ya está en uso.")
        
        if CustomUser .objects.filter(username=self.username).exists():
            raise ValidationError("Este nombre de usuario ya está en uso.")

    def validate_password(self, password):
        """Valida que la contraseña contenga al menos un carácter especial."""
        if not re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
            raise ValidationError("La contraseña debe contener al menos un carácter especial.")

Registro_server/autenticaciones/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django import forms
from django.contrib.auth import get_user_model  # Importa get_user_model

# Formulario para el registro de usuarios
class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput, label="Confirmar contraseña")

    class Meta:
        model = get_user_model()  # Usa el modelo de usuario actual
        fields = ['username', 'email', 'password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Las contraseñas no coinciden")

# Vista de autenticación
def auth_view(request):
    User = get_user_model()  # Obtiene el modelo de usuario actual
    if request.method == 'POST':
        if 'register' in request.POST:
            form = UserRegistrationForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                user.set_password(form.cleaned_data['password'])  # Establecer la contraseña encriptada
                user.save()
                auth_login(request, user)  # Iniciar sesión automáticamente después del registro
                return redirect('autenticaciones:home')  # Redirigir a la vista home
            else:
                return render(request, 'auth.html', {'form': form, 'error': 'Error en el registro', 'errors': form.errors})

        elif 'login' in request.POST:
            email = request.POST.get('email')
            password = request.POST.get('password')
            user = authenticate(request, username=email, password=password)

            if user is not None:
                auth_login(request, user)  # Iniciar sesión
                return redirect('autenticaciones:home')  # Redirigir a la vista home
            else:
                return render(request, 'auth.html', {'error': 'Credenciales incorrectas'})

    else:
        form = UserRegistrationForm()  # Mostrar formulario vacío al acceder por GET

    return render(request, 'auth.html', {'form': form})

@login_required
def home(request):
    return render(request, 'home.html')

def information_view(request):
    return render(request, 'information.html')

def logout(request):  # Renombrar la función de logout
    auth_logout(request)  # Cerrar sesión
    return redirect('autenticaciones:auth_view')  # Redirigir a la vista de autenticación


def about_view(request):
    return render(request, 'about.html') 

autenticaciones/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django import forms
from django.contrib.auth import get_user_model  # Importa get_user_model

# Formulario para el registro de usuarios
class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput, label="Confirmar contraseña")

    class Meta:
        model = get_user_model()  # Usa el modelo de usuario actual
        fields = ['username', 'email', 'password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Las contraseñas no coinciden")

# Vista de autenticación
def auth_view(request):
    User = get_user_model()  # Obtiene el modelo de usuario actual
    if request.method == 'POST':
        if 'register' in request.POST:
            form = UserRegistrationForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                user.set_password(form.cleaned_data['password'])  # Establecer la contraseña encriptada
                user.save()
                auth_login(request, user)  # Iniciar sesión automáticamente después del registro
                return redirect('autenticaciones:home')  # Redirigir a la vista home
            else:
                return render(request, 'auth.html', {'form': form, 'error': 'Error en el registro', 'errors': form.errors})

        elif 'login' in request.POST:
            email = request.POST.get('email')
            password = request.POST.get('password')
            user = authenticate(request, username=email, password=password)

            if user is not None:
                auth_login(request, user)  # Iniciar sesión
                return redirect('autenticaciones:home')  # Redirigir a la vista home
            else:
                return render(request, 'auth.html', {'error': 'Credenciales incorrectas'})

    else:
        form = UserRegistrationForm()  # Mostrar formulario vacío al acceder por GET

    return render(request, 'auth.html', {'form': form})

@login_required
def home(request):
    return render(request, 'home.html')

def information_view(request):
    return render(request, 'information.html')

def logout(request):  # Renombrar la función de logout
    auth_logout(request)  # Cerrar sesión
    return redirect('autenticaciones:auth_view')  # Redirigir a la vista de autenticación


def about_view(request):
    return render(request, 'about.html') 

autenticaciones/templates/auth.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Bio-Analitic-Project</title>
<style>
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-image: url('https://th.bing.com/th/id/R.2ad14523c5b5bdbb0fe540b4592d86c7?rik=DOY8Gi9Fqf8%2fFw&pid=ImgRaw&r=0');
    background-size: cover;
    background-position: center;
}

body::before {
    content: "";
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-image: inherit; /* Hereda la imagen de fondo del body */
    background-size: cover;
    background-position: center;
    filter: blur(8px); /* Efecto de desenfoque */
    z-index: -1; /* Envía la imagen al fondo */
}

.container {
    max-width: 350px;
    margin: 50px auto; /* Centra el contenedor horizontalmente */
    padding: 20px;
    background: rgba(255, 255, 255, 0.9); /* Fondo blanco con opacidad */
    border-radius: 10px;
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
    text-align: center; /* Centra el texto dentro del contenedor */
    position: relative; /* Asegura que el contenedor esté en el flujo del documento */
    z-index: 1; /* Asegura que el contenedor esté por encima del fondo */
}

h2 {
    color: #333;
}

.error {
    color: red;
    margin-bottom: 10px;
}

label {
    margin-top: 10px;
    display: block;
}

input[type="text"],
input[type="email"],
input[type="password"] {
    width: calc(100% - 20px);
    padding: 10px;
    margin-bottom: 15px; /* Aumenta el espacio entre los campos */
    border: 1px solid #ccc;
    border-radius: 4px;
}

button {
    width: 100%;
    padding: 10px;
    margin: 10px 0; /* Espacio entre los botones */
    background-color: #007bff;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s; /* Transición suave para el hover */
}

button:hover {
    background-color: #0056b3;
}

footer {
    text-align: center;
    margin:100px;
    position: relative; /* Asegura que el footer esté en el flujo del documento */
    z-index: 1; /* Asegura que el footer esté por encima del fondo */
}

footer a {
    color: #007bff; /* Color del enlace */
    text-decoration: none; /* Sin subrayado */
}

footer a:hover {
    text-decoration: underline; /* Subrayado al pasar el mouse */
}
</style>
</head>




<body>
    <div class="container">
        <h2>Welcome to Bio-Analitic-Project</h2>
        <h3> Please, login or create an account</h3>

        {% if error %}
            <div class="error">{{ error }}</div>
        {% endif %}

        <form method="POST">
            {% csrf_token %}
        
            <label for="username">Nombre de Usuario:</label>
            <input type="text" id="username" name="username" required>

            <label for="email">Correo Electrónico:</label>
            <input type="email" id="email" name="email" required>

            <label for="password">Contraseña:</label>
            <input type="password" id="password" name="password" required>

            <label for="password_confirm">Confirmar Contraseña:</label>
            <input type="password" id="password_confirm" name="password_confirm" required>

            <button type="submit" name="register">Registrarse</button>
            <button type="submit" name="login">Iniciar Sesión</button>
        </form>
    </div>


    <footer>
        <a href="{% url 'autenticaciones:information' %}">Más información</a>
    </footer>
</body>
</html>

autenticaciones/templates/home.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bio-Analytic Project</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0; /* Elimina márgenes del body */
            padding: 0;
        }

        .navbar {
            background-color: #000000; /* Fondo negro */
            color: white;
            padding: 10px 20px; /* Espaciado interno */
            display: flex;
            align-items: center; /* Centra verticalmente los elementos */
            justify-content: center; /* Centra horizontalmente los elementos */
            position: relative; /* Para el posicionamiento de los enlaces */
        }

        .navbar h2 {
            margin: 0; /* Elimina el margen del título */
            color: white; /* Color del texto del título */
            flex: 1; /* Permite que el título ocupe espacio */
            text-align: left; /* Alinea el título a la izquierda */
        }

        .navbar a {
            margin: 0 15px; /* Espacio entre los enlaces */
            color: white; /* Color de los enlaces */
            text-decoration: none; /* Elimina el subrayado del enlace */
            cursor: pointer; /* Cambia el cursor al pasar sobre el texto */
            transition: color 0.3s; /* Transición suave para el cambio de color */
        }

        .navbar a:hover {
            color: #ddd; /* Cambia el color al pasar el mouse */
        }

        .animated-banner {
            animation: fadeIn 2s, slideIn 1s forwards; /* Añade animación de deslizamiento */
            text-align: center; /* Centra el texto del banner */
            margin: 20px 0; /* Espacio alrededor del banner */
            font-size: 24px; /* Tamaño de fuente */
            color: #333; /* Color del texto */
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }

        @keyframes slideIn {
            from {
                transform: translateY(-20px); /* Desliza desde arriba */
                opacity: 0;
            }
            to {
                transform: translateY(0);
                opacity: 1;
            }
        }

        .options {
            text-align: center; /* Centra el contenido */
            margin: 20px 0; /* Espacio alrededor de las opciones */
        }

        .button {
            display: inline-block;
            padding: 10px 20px;
            background-color: blue; /* Color azul para el botón */
            color: white; /* Color del texto del botón */
            text-decoration: none; /* Elimina el subrayado */
            border-radius: 4px; /* Bordes redondeados */
            transition: background-color 0.3s; /* Transición suave para el color de fondo */
        }

        .button:hover {
            background-color: darkblue; /* Color al pasar el mouse */
        }

        .project-info {
            margin: 40px auto; /* Aumenta el espacio entre el botón y el proyecto y centra el contenedor */
            padding: 15px;
            background-color: #e9ecef; /* Color de fondo para el div de información del proyecto */
            border-radius: 8px;
            text-align: left; /* Alinea el texto a la izquierda */
            max-width: 600px; /* Limita el ancho máximo del contenedor */
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1); /* Sombra para el contenedor */
        }

        .logout-container {
            display: flex; /* Utiliza flexbox para centrar el botón */
            justify-content: center; /* Centra horizontalmente */
            margin-top: 20px; /* Espacio superior para separar del proyecto */
        }

        .logout-button {
            padding: 10px 20px;
            background-color: red; /* Color rojo para el botón de cerrar sesión */
            color: white; /* Color del texto del botón */
            text-decoration: none; /* Elimina el subrayado */
            border-radius: 4px; /* Bordes redondeados */
            transition: background-color 0.3s; /* Transición suave para el color de fondo */
        }

        .logout-button:hover {
            background-color: darkred; /* Color al pasar el mouse */
        }
    </style>
</head>
<body>
    <div class="navbar">
        <h2>Bio-Analytic Project</h2>
        <a href="https://wa.me/1234567890" target="_blank">Contact</a> <!-- Reemplaza con tu número de WhatsApp -->
        <a href="{% url 'sequences:about' %}">About me</a> <!-- Asegúrate de que about.html esté en la misma carpeta -->
    </div>

    <div class="animated-banner">
        <h2>Hi, Welcome to Bio-Analytic Project</h2>
    </div>

    <div class="options">
        <a href="{% url 'sequences:sequence' %}" class="button">Search Sequence</a>
    </div>

    <div class="project-info">
        <h2>About This Project</h2>
        <p>This project is designed to help users search for specific DNA sequences. It provides a user-friendly interface where you can input a DNA sequence and retrieve relevant information. The goal is to facilitate research and education in genetics by making DNA sequence analysis accessible to everyone.</p>
        <p>Whether you are a student, a researcher, or just someone interested in genetics, this tool can assist you in understanding DNA sequences better. We hope you find it useful!</p>
        <p>This project connects to the NCBI API to extract information based on the provided DNA sequence, which is validated before processing. The extracted data is then stored in a database for easy access and further analysis.</p>
    </div>

    <div class="logout-container">
        <a href="{% url 'autenticaciones:logout' %}" class="logout-button">Cerrar sesión</a>
    </div>

</body>
</html>

autenticaciones/templates/information.html
<!-- information.html -->
{% extends "base.html" %}

{% block content %}
<h2>Información</h2>
<p>Aquí puedes agregar información relevante para los usuarios.</p>
{% endblock %}

autenticaciones/templates/logout.html
<!-- logout.html -->
{% extends "base.html" %}

{% block content %}
<h2>Cerrar Sesión</h2>
<p>Has cerrado sesión correctamente. <a href="{% url 'auth_view' %}">Volver a la página de autenticación</a></p>
{% endblock %}